/* Generated By:JavaCC: Do not edit this line. AnalizadorConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 1;
  /** RegularExpression Id. */
  int STATIC = 2;
  /** RegularExpression Id. */
  int VOID = 3;
  /** RegularExpression Id. */
  int MAIN = 4;
  /** RegularExpression Id. */
  int STRING = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int FLOAT = 7;
  /** RegularExpression Id. */
  int CHAR = 8;
  /** RegularExpression Id. */
  int INTEGER = 9;
  /** RegularExpression Id. */
  int PARSEINT = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int FOR = 12;
  /** RegularExpression Id. */
  int TRUE = 13;
  /** RegularExpression Id. */
  int FALSE = 14;
  /** RegularExpression Id. */
  int BOOLEAN = 15;
  /** RegularExpression Id. */
  int ELSE = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int RETURN = 18;
  /** RegularExpression Id. */
  int IMPORT = 19;
  /** RegularExpression Id. */
  int NULL = 20;
  /** RegularExpression Id. */
  int LENGTH = 21;
  /** RegularExpression Id. */
  int DO = 22;
  /** RegularExpression Id. */
  int SWITCH = 23;
  /** RegularExpression Id. */
  int CASE = 24;
  /** RegularExpression Id. */
  int BREAK = 25;
  /** RegularExpression Id. */
  int NUMERODECIMAL = 26;
  /** RegularExpression Id. */
  int ID = 27;
  /** RegularExpression Id. */
  int NEGEX = 28;
  /** RegularExpression Id. */
  int MODULO = 29;
  /** RegularExpression Id. */
  int TEXTO = 30;
  /** RegularExpression Id. */
  int NUMERO = 31;
  /** RegularExpression Id. */
  int FINLINEA = 32;
  /** RegularExpression Id. */
  int COMA = 33;
  /** RegularExpression Id. */
  int GUIONES = 34;
  /** RegularExpression Id. */
  int ABRIRLLA = 35;
  /** RegularExpression Id. */
  int CERRARLLA = 36;
  /** RegularExpression Id. */
  int ABRIRPAR = 37;
  /** RegularExpression Id. */
  int CERRARPAR = 38;
  /** RegularExpression Id. */
  int ABRIRCOR = 39;
  /** RegularExpression Id. */
  int CERRARCOR = 40;
  /** RegularExpression Id. */
  int PUNTO = 41;
  /** RegularExpression Id. */
  int DOSPUNTOS = 42;
  /** RegularExpression Id. */
  int MAS = 43;
  /** RegularExpression Id. */
  int MENOS = 44;
  /** RegularExpression Id. */
  int POR = 45;
  /** RegularExpression Id. */
  int ENTRE = 46;
  /** RegularExpression Id. */
  int NEGAR = 47;
  /** RegularExpression Id. */
  int COMILLAS = 48;
  /** RegularExpression Id. */
  int MAYORQUE = 49;
  /** RegularExpression Id. */
  int MENORQUE = 50;
  /** RegularExpression Id. */
  int IGUAL = 51;
  /** RegularExpression Id. */
  int OR = 52;
  /** RegularExpression Id. */
  int AND = 53;
  /** RegularExpression Id. */
  int ALGO = 54;
  /** RegularExpression Id. */
  int MENORIGUAL = 55;
  /** RegularExpression Id. */
  int MAYORIGUAL = 56;
  /** RegularExpression Id. */
  int IGUALIGUAL = 57;
  /** RegularExpression Id. */
  int DIFERENTEDE = 58;
  /** RegularExpression Id. */
  int ERROR_DECIMAL = 68;
  /** RegularExpression Id. */
  int ERROR_ID = 69;
  /** RegularExpression Id. */
  int ERROR_SIMBOLO = 70;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int Comentario = 1;
  /** Lexical state. */
  int ComentarioLineas = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"class\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"String\"",
    "\"int\"",
    "\"float\"",
    "\"char\"",
    "\"Integer\"",
    "\"parseInt\"",
    "\"if\"",
    "\"for\"",
    "\"true\"",
    "\"false\"",
    "\"boolean\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"import\"",
    "\"null\"",
    "\"length\"",
    "\"do\"",
    "\"switch\"",
    "\"case\"",
    "\"break\"",
    "<NUMERODECIMAL>",
    "<ID>",
    "\"!\"",
    "\"%\"",
    "<TEXTO>",
    "<NUMERO>",
    "\";\"",
    "\",\"",
    "<GUIONES>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\":\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"~\"",
    "\"\\\"\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\"|\"",
    "\"&\"",
    "\"\\\\\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"//\"",
    "\"/*\"",
    "<token of kind 61>",
    "<token of kind 62>",
    "\"*/\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<ERROR_DECIMAL>",
    "<ERROR_ID>",
    "<ERROR_SIMBOLO>",
  };

}
